# drop user jen@localhost;
# create user 'jen'@'localhost' identified by 'jen';
# grant all privileges on pottyproject.* to 'jen'@'localhost';
# flush privileges;

default:
  adapter: sqlite3
  database: pottyproject.db

development:
  adapter: sqlite3
  database: pottyproject.db

production:
  adapter: sqlite3
  database: pottyproject.db